In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
# x = [0,1,2,3,4,5,6,7,8,9]
# 1차원 데이터
x = np.arange(10)
print(x)
print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [4]:
# 2차원 데이터
x = np.arange(10).reshape(-1, 1)
print(x)
print(x.shape)
# reshape 함수는 파라미터로 입력한 차원에 맞게 데이터를 자동으로 맞춘다

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [5]:
y = (2*x + 1).reshape(-1, 1)

In [6]:
print(y)
print(y.shape)

[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]]
(10, 1)


## 모델의 선언, fit(학습), predict(예측)

In [7]:
# 모델 선언
model = LinearRegression()

In [8]:
model

LinearRegression()

In [9]:
# 학습
model.fit(x, y)

LinearRegression()

In [10]:
# 예측
prediction = model.predict([[10.0]])

In [11]:
prediction

array([[21.]])